### ISSUE TITLE
Unify `web-dir`, `vendor-dir`, `bin-dir` in `composer.json` across extensions, documentation, etc

### ISSUE THREAD

**Issue by sypets** [TYPO3-Documentation/tea#802]
example composer.json

```
"extra": {
    "typo3/cms": {
        "web-dir": ".Build/Web"
...

```

Might make sense to also specify:

```
"vendor-dir": ".Build/vendor",
"bin-dir": ".Build/bin",

```

## Todos

* [x] make decision
* [x]  update the official extensions listed below (if necessary): 
  * [x] tea: PR #807
  * [x] examples: PR https://github.com/TYPO3-Documentation/t3docs-examples/pull/177
  * styleguide (no change necessary)
  * enetcache  (no change necessary)
  * [x] news (not official, but can make PR) PR: https://github.com/georgringer/news/pull/2078
* [ ]  check documentation and update to use the standard
  *  extension composer.json: https://docs.typo3.org/m/typo3/reference-coreapi/main/en-us/ExtensionArchitecture/FileStructure/ComposerJson.html
  * ...

## Proposal

~~My proposal is to use .Build/public but will check in core channel.~~ (See below)

* web-dir:` .Build/Web`
* vendor-dir: .`Build/vendor`
* bin-dir: `.Build/bin`

## Currently used web-dir

| package   | used web-dir | vendor-dir | bin-dir  |
| -------------- | ------------------- | --------------- | ----------- |
| [tea](https://github.com/TYPO3-Documentation/tea/blob/main/composer.json)  | .Build/public | .Build/vendor | not specified, uses default .Build/vendor/bin |
|  [EXT:styleguide](https://github.com/TYPO3/styleguide) |  .Build/Web | .Build/vendor | .Build/bin |
| docs [examples](https://github.com/TYPO3-Documentation/t3docs-examples) | .Build/web| .Build/vendor |.Build/bin |
| [enetcache](https://github.com/lolli42/enetcache/blob/main/composer.json) | .Build/Web |  .Build/vendor |.Build/bin |
| [news](https://github.com/georgringer/news/) | .Build/public |  .Build/vendor |.Build/bin |

* So there are currently 3 differently used web-dirs (1) .Build/public, (2)  .Build/Web and (3) .Build/web in the 4 selected extensions :frowning_face: 

* for ` vendor-dir` and `bin-dir` it is mostly the same, except for tea which has not defined bin-dir

## Motiviation

It is sometimes a PITA to contribute to extensions if this is not unified. Often the target dir must be used or is used in some configuration file (such as phpstan.neon or runTests.sh) and then often no web-dir is specified or something else is used.

This is to be a recommended "best practice" where it is still possible to do it differently, but it is intended to facilitate contribution to do it the standard way.

## which extensions are "official"

I listed the above extensions for the following reason (all except "news" have some official status for the following reasons):

* tea is propagated as best practice
* styleguide is a non-system extension but used in core and (mostly) maintained by core people
* news:  highly used community extension
* docs examples: is official examples extension of Documenation Team and used as example
* enetcache is used in official documentation "[Extension testing](https://docs.typo3.org/m/typo3/reference-coreapi/main/en-us/Testing/ExtensionTesting.html)"

The following I would consider as official: tea, examples. enetcache is not official but used in official documentation as example.

**Comment by sypets** [comment]
I am working on this, you can put me as "assigned" (I don't have the permissions here, though I do have permissions to change assigned or add labels in other repos in TYPO3-Documentation).

**Comment by oliverklee** [comment]
Thank you for working on making this consistent!

**Comment by sypets** [comment]
Update: analysis of existing extensions. This is a very crude first result and only uses 20 extensions.

I used the top 20 liked extensions from https://extensions.typo3.org which are compatible with v12. These are more the "cutting edge" extensions, so it is a little biased.

| web-dir  | number |
| ------------ | ------------ |
| .Build/Web | 6 of 20 |
| .Build/public | 3 of 20 |
| public   | 1 of 20 |
| .Build/web | 1 of 20 |



## Workflow for analysis

1. get top 20 from https://extensions.typo3.org
2. fetch

```
git clone git@github.com:maikschneider/bw_captcha.git
git clone git@github.com:b13/container.git
git clone git@github.com:IchHabRecht/content_defender.git
git clone git@github.com:sebkln/content_slug.git
git clone git@github.com:clickstorm/cs_seo.git
git clone git@github.com:mhirdes/go_maps_ext.git
git clone git@github.com:in2code-de/lux.git
git clone git@github.com:in2code-de/luxletter.git
git clone git@github.com:Gernott/mask.git
git clone git@github.com:georgringer/news.git
git clone https://bitbucket.org/99grad/nnhelpers.git
git clone https://bitbucket.org/99grad-team/nnrestapi.git
git clone git@github.com:brotkrueml/schema.git
git clone git@github.com:derhansen/sf_event_mgt.git
git clone git@github.com:lochmueller/sourceopt.git
git clone git@github.com:xperseguers/t3ext-image_autoresize.git
git clone git@github.com:rrrapha/translate_locallang.git
git clone git@github.com:TYPO3-Console/TYPO3-Console.git
git clone git@github.com:DirkPersky/typo3-dp_cookieconsent.git
git clone git@github.com:WapplerSystems/ws_scss.git

```

3. get results

`grep web-dir */composer.json  | perl -p -e "s/.*\"web-dir\": \"([^\"]*)\".*/\1/" | sort | uniq -c | sort -n
`

**Comment by sypets** [comment]
preliminary decision: `.Build/Web`

* is used in majority of top 20 extensions
* differentiate between a .Build web dir and a project web dir (public)

**Comment by sypets** [comment]
I am closing now. It is mostly done. I added PR for tea and the documentation "examples" extension (merged) and added PR for news https://github.com/georgringer/news/pull/2078 (not merged yet). 

There are probably still some place where one can create PR (e.g. extension_builder) and I will keep working on it a bit, but would consider it done.
